"""add document metadata

Revision ID: 192f71599e7b
Revises: 795bc26ab32e
Create Date: 2026-07-02 10:58:14.968393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192f71599e7b'
down_revision: Union[str, Sequence[str], None] = '795bc26ab32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('category', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'category')
    op.drop_column('documents', 'department')
    # ### end Alembic commands ###
