"""update document model

Revision ID: a9612fa39e5e
Revises: 931de75a67c5
Create Date: 2026-06-27 07:44:14.933330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9612fa39e5e'
down_revision: Union[str, Sequence[str], None] = '931de75a67c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('storage_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('documents', 'file_path')
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'storage_path')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'file_type')
    # ### end Alembic commands ###
