"""add multi tenancy

Revision ID: d9dca0135b6e
Revises: 18e6a6cd27a2
Create Date: 2026-06-30 11:23:04.199077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9dca0135b6e'
down_revision: Union[str, Sequence[str], None] = '18e6a6cd27a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.add_column('conversations', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'tenants', ['tenant_id'], ['id'])
    op.add_column('document_chunks', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_document_chunks_tenant_id'), 'document_chunks', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'tenants', ['tenant_id'], ['id'])
    op.add_column('documents', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'tenants', ['tenant_id'], ['id'])
    op.add_column('messages', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_column('messages', 'tenant_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_column('documents', 'tenant_id')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_tenant_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'tenant_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_column('conversations', 'tenant_id')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
