"""add conversation memory fields

Revision ID: f130026de336
Revises: 9b8880d96422
Create Date: 2026-07-11 13:05:56.422233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f130026de336'
down_revision: Union[str, Sequence[str], None] = '9b8880d96422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column(
        "conversations",
        sa.Column(
            "message_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'conversation_metadata')
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'message_count')
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
